### ISSUE TITLE
[BUG] Cannot link to correct file

### ISSUE THREAD

**Issue by Quorafind** [ozntel/oz-image-in-editor-obsidian#1]
When I wanted to use ![[]] to link to my jpg file.

And it will output a link like this:

![image](https://user-images.githubusercontent.com/13215013/115981033-84ca7a80-a5c3-11eb-878f-928df5c9c9d9.png)

It only generate `jpg` and there is no `myfile`

----

EDIT 1 : I used a Chinese character to name this jpg file. Maybe this cause error.

You can use `图片.jpg` to test?

**Comment by ozntel** [comment]
Hi @Quorafind, can you try again? I corrected the regex for checking the characters.
