### ISSUE TITLE
Is PDF support a possibility too?

### ISSUE THREAD

**Issue by GitMurf** [ozntel/oz-image-in-editor-obsidian#10]
Amazing job on this plugin! I am curious if you think PDF rendering is possible too?

**Comment by ozntel** [comment]
Hi @GitMurf, thank you. I am glad to hear that the plugin is helpful.
I might think to implement the PDF render option in the future, however, it requires time since PDF is a little bit unique when it comes to rendering from the local files. But I will add into my enhancement list 🙂

**Comment by ozntel** [comment]
Hi @GitMurf, I just released a version with an experimental feature to render PDF files in the Editor. Please update the plugin in Obsidian and turn on the option from the Plugin Settings tab. 
Hope this helps!
