### ISSUE TITLE
1.7.2 version messes up cursor location in all text after transclusion block

### ISSUE THREAD

**Issue by guategeek** [ozntel/oz-image-in-editor-obsidian#100]
In the newest update of the plugin (1.7.2) when using the transclusion feature the cursor no longer lines up with all text below a transclusion. This was not the case with the previous (1.7.1) version of the plugin.

See here how the cursor is located above the line of text:
![Cursor Problems](https://user-images.githubusercontent.com/868801/145423404-dab4871c-b199-447c-96fd-54ba38ea907c.png)

**Comment by ozntel** [comment]
It should be fixed in the new release. Margin of transclusion within the new styling somehow was causing it. Let me know if the issue persists.
