### ISSUE TITLE
Not compatible with New Obsidian Editor

### ISSUE THREAD

**Issue by JamesO2x** [ozntel/oz-image-in-editor-obsidian#102]
The new "Live Preview" editor has its own "image preview in editor". But I don't really like how it hides the image source in this view, and prefer the behavior of Ozan's Image Preview. 

Despite "Source Mode" looking identical, it doesn't seem to be compatible with Ozan's Image in Editor Plugin. So I have to switch ,y whole vault to Legacy Mode for this plugin to work.

It would be nice to see an update to this plugin that's compatible with the new Source Mode editor.

**Comment by ozntel** [comment]
I included support for the Source Mode just yesterday. You can check the issue for the details: https://github.com/ozntel/oz-image-in-editor-obsidian/issues/101

You can also find the video there in case it doesn't work after update.

Let me know in case you still have a trouble.

**Comment by JamesO2x** [comment]
Oh shoot, I forgot to respond here. 
I just updated the plugin and its still not working. I followed all the instructions posted in the other thread you linked.
I'm gonna try a system restart and see if that kicks it in, as chrisgrieser mentioned it might be a cache issue or something.

Ok, I just did a full system restart and this plugin is still not working. Not sure what else to try.

**Comment by ozntel** [comment]
Can you try to open Obsidian Developer tools (from View menu on the top) and inside press "CTRL+R" in Windows or "CMD+R" in Mac? 
As far as I remember, only it helped in such situation.

**Comment by JamesO2x** [comment]
> Can you try to open Obsidian Developer tools (from View menu on the top) and inside press "CTRL+R" in Windows or "CMD+R" in Mac? As far as I remember, only it helped in such situation.

I'm a little confused on what you're asking here. `CTRL+R` doesn't open Developer Tools, `CTRL+R` reloads the vault. Do you mean `CTRL+SHIFT+I` like mentioned here: [How to access Developer Tools in v0.8.14? - Resolved help - Obsidian Forum](https://forum.obsidian.md/t/how-to-access-developer-tools-in-v0-8-14/5820)

Also not sure what you are referencing with "from View menu on the top" - There is no menu or button labeled "view" at the top of the the Obsidian window.

If you mean in the "Developer Tools", the tabs at the top are labeled:
Elements, Console, Sources, Network, Performance, Memory, Application, Security, Lighthouse.

Not sure if this will help, but the Console window shows this:
```
Obsidian Developer Console
VM1454:334 Image in Editor Plugin is loaded
```

I have all other plugins disabled.

Here is an example image of my note:

![image](https://user-images.githubusercontent.com/29412392/149234441-50461436-aee4-4b35-9f22-c2c6875e9f12.png)

Image does not show in Source Mode. Image displays fine in Live Preview or Reading mode:
![image](https://user-images.githubusercontent.com/29412392/149234611-6cf0a34f-1bd7-4a16-8fa0-1bf22707376e.png)
