### ISSUE TITLE
Problem with Chinese typing

### ISSUE THREAD

**Issue by freezoc** [ozntel/oz-image-in-editor-obsidian#104]
Obsidian v0.13.14, Oz-image-in-editor-obsidian v2.0.5.
Typing in Chinese causes something strange, like the following:
![动画](https://user-images.githubusercontent.com/20424296/147812426-1b650e35-73af-46fc-8a7a-b4553c415008.gif)
This problem occurred after Oz-image-in-editor-obsidian was updated to v2.0. 
When turning off the Oz-image-in-editor-obsidian plugin, the problem is gone.

**Comment by zhao1iang** [comment]
ME TOO!!

**Comment by huang5556019** [comment]
me too

**Comment by ozntel** [comment]
I don't understand much what is happening but I just released a version, in which I totally changed the way of working. Does the issue still persists?

**Comment by freezoc** [comment]
The problem seems to have been solved by the updating. Thanks.

**Comment by ozntel** [comment]
Happy to hear that!
