### ISSUE TITLE
Good Feature: Add % to resize and render image

### ISSUE THREAD

**Issue by fengyuan213** [ozntel/oz-image-in-editor-obsidian#110]
For example, I have a filename of screenshot of my desktop, it's name is `pic1.jpg` It has size of **300x300** px and I want it to be **150x150** pixels.
To achieve that, I need to use tag:  `![[pic1.jpg|150x150]]`. It is complicated and I need to know the image size for every specific image.
Is it possible to add a small feature to just use something like: `![[pic1.jpg|50%]]` to achieve the same effect or something similar?

**Comment by ozntel** [comment]
You can use `#small` (%75), `#x-small` (%50) or `#xx-small` (%25) as an alt text to resize your images with percentages. If you install additionally **Style Settings Plugin**, you can also customize these percentages for each alt text separately:

<img width="501" alt="image" src="https://user-images.githubusercontent.com/55187568/222977809-85532db8-97e9-4e93-90dd-47653bc38930.png">
