### ISSUE TITLE
Obsidian Release v1.0.0 - plugin doesn't work anymore

### ISSUE THREAD

**Issue by Davidb-2107** [ozntel/oz-image-in-editor-obsidian#113]
Hello,

Since I have made the update, the editor mode doesn't show a preview of my images anymore.

Are you aware of that or I'm the only one?

Thanks

**Comment by ozntel** [comment]
It should work. Can you try to restart your vault? Are you using on your mobile or desktop?

**Comment by Davidb-2107** [comment]
I've started my vault and everything went fine. Thanks for your time

**Comment by ozntel** [comment]
Thanks for confirming
