### ISSUE TITLE
#small not working?

### ISSUE THREAD

**Issue by limex** [ozntel/oz-image-in-editor-obsidian#115]
Hi,
Expected:
`![#small](t1.jpg)`
should change the size of the image t1.jpg 

Observed:
Image is rendered ignoring the #small directive.
![image](https://user-images.githubusercontent.com/1173039/197491015-f2f38d03-6e7c-41e7-ba77-2f69485fcefe.png)

Sidenote:
Extension ist active, because 
`![100](t1.jpg)`
is working correct.

Please advice how to fix issue

**Comment by ozntel** [comment]
It is working actually. Are you sure you are using the image from Image in Editor plugin and not Live Preview? 
If Live Preview is enabled, Image in Editor plugin won't render anything to avoid duplicates.
