### ISSUE TITLE
any possible to support local pdf not in vault?

### ISSUE THREAD

**Issue by ChitaGideon** [ozntel/oz-image-in-editor-obsidian#116]
maybe something like
```
![[file:///Users/xxx/Downloads/1.pdf]]
```
or 
```
![](file:///Users/xxx/Downloads/1.pdf#page=12)
```

**Comment by ozntel** [comment]
It is included in the new release. You can either use `file:///` or `app://local/`. Thanks

**Comment by j-maffe** [comment]
Could youplease elaborate on how to do this with an example? I couldn't get it to work. It might be a good idea to state it as a feature in the readme since I think it's a very significant addition :D

**Comment by ChitaGideon** [comment]
I try it with code :`![](file:///Users/yhr/Downloads/Mahinda_Bhikkhu-Meditation_Method.pdf)`
and error :
<img width="372" alt="image" src="https://user-images.githubusercontent.com/1167456/217454626-0220dba9-2781-40b8-878c-d202a22a17f2.png">
But if I write more words before the link like: `a1 ![](file:///Users/yhr/Downloads/Mahinda_Bhikkhu-Meditation_Method.pdf)`
it works.

**Comment by j-maffe** [comment]
Doesn't work with me :/ No error message, just fails to show anything.

**Comment by ChitaGideon** [comment]
And in reading view , it can not work

**Comment by Ume-Saruma** [comment]
@j-adel hey is it still not working for you? I'm in a similar situation.

**Comment by g-adel** [comment]
> @j-adel hey is it still not working for you? I'm in a similar situation.

No, sorry. I've stopped using this plugin. To be honest I just found that placing all of the necessary files in the vault has worked out.

**Comment by Ume-Saruma** [comment]
> No, sorry. I've stopped using this plugin. To be honest I just found that placing all of the necessary files in the vault has worked out.

Oh great then! For me since I'm using locally synced files I can't put them into the obsidian folder... I hope this issue is resolved soon.
