### ISSUE TITLE
[BUG]  Duplicate Rendering Issue

### ISSUE THREAD

**Issue by hacker-jerry** [ozntel/oz-image-in-editor-obsidian#117]
After updating the latest version of obsidian, in the real-time preview mode, if there is text in front of the reference of the picture, for example:

` a picture here: ![[Pasted Picture]].`

It will render like this:

<img width="768" alt="image" src="https://user-images.githubusercontent.com/57279550/203329900-bb075df7-cf80-4ec4-ba6d-859afb4e84b7.png">

But in source-view mode, there's no issue.

<img width="775" alt="image" src="https://user-images.githubusercontent.com/57279550/203330151-50807b13-3e78-4b93-abc8-edfd89ebbf7b.png">

**Comment by ozntel** [comment]
This plugin only adds image to Source Mode. For Live Preview you need to contact with Obsidian's developer, most probably on Discord. Thanks
