### ISSUE TITLE
Update README 

### ISSUE THREAD

**Issue by ggstrader** [ozntel/oz-image-in-editor-obsidian#118]
It's not obvious what exactly this plugin does that Live Preview doesn't. AFAICT it doesn't do anything other than maybe Excalidraw previews. I used to use this plugin before Live Preview, but just realized I've had it disabled for over a year and haven't noticed any benefits re-enabling it.

The readme should make it clearer why exactly someone would want to use it.

**Comment by ozntel** [comment]
Just updated and added a note at the beginning of the README file. It should also appear in the community plugins description. Thanks
