### ISSUE TITLE
hiding images in folded lines

### ISSUE THREAD

**Issue by PSEUDO-SAPPHO** [ozntel/oz-image-in-editor-obsidian#119]
Does it exist a preference to turn off displaying for images within folded lines?

![image](https://user-images.githubusercontent.com/82666844/222942688-f3889302-4abf-49be-b1de-3f6c577e63d4.png)

![image](https://user-images.githubusercontent.com/82666844/222942695-68cfeb4b-5e3d-4873-b4ea-82006b11a164.png)

After folding line, still the image will appear as you see it.

**Comment by ozntel** [comment]
The new release should help to hide the images in the folded lines
