### ISSUE TITLE
Hope for supporting [[Internal link]] function

### ISSUE THREAD

**Issue by Callioper** [ozntel/oz-image-in-editor-obsidian#12]
Amazing job with Picture and PDF. 
And I am curious that is [[Internal link]] in your roadmap?

**Comment by ozntel** [comment]
Hi @Callioper happy to hear that the plugin helps.
I couldn't understand exactly. Can you try to explain on an example what feature you are expecting?

**Comment by Callioper** [comment]
Obsidian help describes [Internal link](https://help.obsidian.md/How+to/Internal+link) like this:

> Internal links are the backbone of your knowledge network.
> Link to files
> To create an internal link, simply type [[. This will prompt you with the list of notes you can link to. Use Up arrow and Down arrow to navigate the suggestion list and Enter to select the current highlighted link.

Now we can use internal link like [[My Page]] or ![[My Page]] to view content under the Preview mode, I expect to view [[My Page]] under the Editor mode.

It may not exactly related to this plugin. Anyway, thanks for your patIence and wonderful job.

**Comment by ozntel** [comment]
Oh, you mean reference for markdown files and their previews when you hover on the link. 
The plugin supports the internal links but only for images and PDF files. Unfortunately it is a little bit out of scope for the plugin to support markdown file preview. But I will keep in mind for the future, thanks for your suggestion 🙂
