### ISSUE TITLE
[Bug] Error when using the plugin

### ISSUE THREAD

**Issue by LBF38** [ozntel/oz-image-in-editor-obsidian#125]
Hello, thanks for the great plugin. I have used it for a while and now, it doesn't work anymore.
Please find below a screenshot of the error: 
![image](https://github.com/ozntel/oz-image-in-editor-obsidian/assets/96347823/a63d0cbc-f3d4-49ff-b985-afb6a91ebd75)

The cursor doesn't change on mouse hover on an image. I have tried to remove any other plugins or themes, but it still doesn't work.

**Comment by Ume-Saruma** [comment]
Hey! Is the plugin working fine for you know? What error were you facing? I'm also having the same issue.
Even if it was a user error could you provide your solution for it?
