### ISSUE TITLE
 Show embedded page, section, and block in edit mode. 

### ISSUE THREAD

**Issue by YQGong** [ozntel/oz-image-in-editor-obsidian#13]
Is it possible to show embedded page, section, and block in edit mode? And, what about edit embedded items in edit mode?

I think this feature will change obsidian's workflow.

**Comment by ozntel** [comment]
Hi @YQGong Thanks for the suggestion. 
For the moment, I am afraid it is a little bit out of scope for the plugin, however, I will definitely add in my roadmap for future development to see what we can do.
Thanks!

**Comment by ozntel** [comment]
Similar Request #12
