### ISSUE TITLE
Cannot reload excalidraw Automatically

### ISSUE THREAD

**Issue by Quorafind** [ozntel/oz-image-in-editor-obsidian#16]
If I change stuff in a excalidraw file, the ![[]] in a file will not update.

**Comment by ozntel** [comment]
Hi,

It is normal behavior. After you make a change in the file, you need to trigger manually an update in the line. The best way to do this is to hit the space button after the markdown `syntax ![[]]`. It will then check if the image changed and change the preview if necessary.

Overall there are 3 types of triggers to load the image:

1. Vault to be loaded (checks all open files)
2. Markdown file to be opened (checks only the opened file)
3. Line text to be changed (checks only the line-edited)

Adding an additional trigger to observe file changes would be consuming for the computer.

Hope this helps.

**Comment by ozntel** [comment]
Duplicate #9

**Comment by zsviczian** [comment]
You could actually do something like this:
- add an event listner to vault.on("modify")
- trigger a custom DOM event targeted to your widgets
- add an event listner to your widgets to reload the image on the custom event

https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/740ff8df6fa8eb6cbca33927db8303d1fd297ad2/src/main.ts#L495

https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/740ff8df6fa8eb6cbca33927db8303d1fd297ad2/src/main.ts#L649

https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/740ff8df6fa8eb6cbca33927db8303d1fd297ad2/src/main.ts#L173

**Comment by ozntel** [comment]
Hi @zsviczian, I just added an option for loading the images again once the original drawings/images are updated. However, it is optional in the settings. I personally won't be using this feature 🙂 Let me know if you catch any issue

**Comment by zsviczian** [comment]
Great! 
Note images are not showing in the readme!
![image](https://user-images.githubusercontent.com/14358394/119248220-f9c3ac80-bb8f-11eb-9747-2ffe11bb7272.png)

**Comment by MasonMcGill** [comment]
Hi, Thanks so much for implementing this, but I can't seem to find the "Refresh Images after Changes" option. I'm using version 2.1.6 of the plugin, with Obsidian 1.1.9.

![image](https://user-images.githubusercontent.com/1045041/215252847-4f89b1da-95c5-40f1-adc0-ce3e018545e5.png)
