### ISSUE TITLE
[Suggestion] Right click to copy image to clipboard

### ISSUE THREAD

**Issue by Yaozhuwa** [ozntel/oz-image-in-editor-obsidian#18]
Your amazing plugin really help me a lot!

## Feature suggestion 1: Right click to copy image to clipboard
When right click the image in Editor or Preview mode, there will be a pop-up menu  on which we can choose to copy the image to the system clipboard.

Sometimes we need to share a image of our obsidian note, but now we need first show the image file in side bar, then open the system file explore to copy it. It's too complex.

![image](https://user-images.githubusercontent.com/28787183/119076597-6a01ef00-ba25-11eb-8dd7-b1faf200e2f4.png)
## Feature suggestion 2: Support pop-up menu in Preview mode.
I just test obsidian and find that the pop-up menu only work in Edit mode (see fig abov)

**Comment by ozntel** [comment]
Hi, I am glad the plugin is helpful.

Once the WYSIWYG feature for Obsidian is released, this plugin will not be in use anymore. Hence, right-click copy feature might be a time investment from my side that won't be used anymore. But I will keep it in mind to see if I can do it simply in the near future.

For the second feature you mentioned above, unfortunately, I don't manipulate anything within the Preview mode with the plugin. You might raise this suggestion to the Obsidian team maybe?

**Comment by ozntel** [comment]
I just release a version that includes an option to copy local images to the clipboard. Hope it helps.
