### ISSUE TITLE
Update docs to other supported image size formats e.g. ![[image.png|100]]

### ISSUE THREAD

**Issue by neurosock** [ozntel/oz-image-in-editor-obsidian#19]
Please consider updating the documentation to reflect the following additional formats which work for me at least (Windows 10, Obsidian v 0.12.3)
```
![[image.png|100]]
![[image.png|100x100]]
![img|100](img/image.png)
![img|100x30](img/image.png)
```
Thanks for the great plugin!

**Comment by neurosock** [comment]
Oops, sorry I just saw this was added to the docs this morning, feel free to close this issue!

**Comment by ozntel** [comment]
Hi, I am glad the plugin is helpful.
I just included this feature, hence, updated the plugin documentation recently. It only includes samples for alt text actually. I'd rather not give all possibilities as a list to ensure that the documentation doesn't frighten users 🙂
