### ISSUE TITLE
[BUG] excalidraw view in list doesn‘’t work as expected

### ISSUE THREAD

**Issue by Yaozhuwa** [ozntel/oz-image-in-editor-obsidian#21]
![Peek 2021-05-22 01-07](https://user-images.githubusercontent.com/28787183/119174345-0ca88500-ba9b-11eb-9949-425cf90268a9.gif)

The bug is shown in fig above.

Test in obsidian v0.12.3, ubuntu18.04

**Comment by ozntel** [comment]
Please update your plugin from community plugins. The new update should solve this issue.
