### ISSUE TITLE
Make the plugin available for mobile

### ISSUE THREAD

**Issue by HEmile** [ozntel/oz-image-in-editor-obsidian#22]
The plugin cannot currently be installed on mobile because manifest.json has desktoponly set to true. I browsed through the code and couldn't quickly find a reason why it can't be available on mobile. Any chance you can change this?

**Comment by ozntel** [comment]
Unfortunately Obsidian uses CodeMirror 6 for the mobile while desktop uses CodeMirror 5. Unfortunately, the methods like `iterateCodeMirrors` or `registerCodeMirror` don't work anymore in CM6. The API for CM6 is also not enough to manipulate the line widgets yet. Therefore, the mobile version won't work even if I change the `manifest.json`

**Comment by ankushg** [comment]
Now that there's some CM6 support in here, is it possible to use in mobile?

**Comment by ozntel** [comment]
It is possible only if you are insider. Right now you need to manually change "only for desktop" flag to false in manifest.json of the plugin but it will work only if you have the insider version of Obsidian. Once the mobile version with the new API will be officially released for everyone, I will also open plugin for mobile usage
