### ISSUE TITLE
Failed to load resource: net::ERR_FILE_NOT_FOUND render-toggle-settings.png

### ISSUE THREAD

**Issue by zsviczian** [ozntel/oz-image-in-editor-obsidian#23]
![image](https://user-images.githubusercontent.com/14358394/119248650-dfd79900-bb92-11eb-9c90-5fc75f563bc7.png)

**Comment by ozntel** [comment]
Oh, I forgot to change the links. Now they should be visible in Obsidian, as well 🙂
