### ISSUE TITLE
Plugin does not work on iPad

### ISSUE THREAD

**Issue by timjore** [ozntel/oz-image-in-editor-obsidian#25]
It would be really helpful if this plugin could be refactored such that it could run on iOS, not just the desktop app.

**Comment by ozntel** [comment]
Hi @timjore, unfortunately, Obsidian uses CodeMirror 6 for the mobile while desktop uses CodeMirror 5.  The common methods for manipulation of the CM5 don't work anymore in CM6. The API for CM6 is also not enough to manipulate the line widgets yet. Therefore,  it is not possible for me just yet to support the mobile apps. However, once Obsidian has native WYSIWYG support, hopefully there is not going to be a need for installing my plugin :)

**Comment by ozntel** [comment]
Duplicate #22
