### ISSUE TITLE
Installation mobile not allowed

### ISSUE THREAD

**Issue by thomaskern** [ozntel/oz-image-in-editor-obsidian#26]
Hi,

when trying to install the plugin on my mobile device (ios; iphone xs max) it fails to install it with the error message that the device is not supported.

See the screenshot: 
![image0](https://user-images.githubusercontent.com/39680/120015774-0444d280-bfe4-11eb-8f04-f1c900ad7c2b.jpg)

BR

**Comment by ozntel** [comment]
Hi, unfortunately, Obsidian uses CodeMirror 6 for the mobile while desktop uses CodeMirror 5. The common methods for manipulation of the CM5 don't work anymore in CM6. The API for CM6 is also not enough to manipulate the line widgets yet. Therefore, it is not possible for me just yet to support the mobile apps. However, once Obsidian has native WYSIWYG support, hopefully, there is not going to be a need for installing my plugin :)

**Comment by ozntel** [comment]
Duplicate #22

**Comment by thomaskern** [comment]
@ozntel sorry, i overlooked #22. thanks for the swift reply.
