### ISSUE TITLE
collapsing header will still show image

### ISSUE THREAD

**Issue by FriedrichStein** [ozntel/oz-image-in-editor-obsidian#29]
Love the plug-in!
But I ran into a problem: 
When I have a picture under a heading, the picture sometimes still shows up when I collapse the header and there is no way to hide it. 
![ImageView](https://user-images.githubusercontent.com/53973194/120792085-4797c780-c535-11eb-8e2a-14d8641e5eff.gif)

Greetings Friedrich

**Comment by ozntel** [comment]
Can you update the version from community plugins and try again? I included a feature to hide widget together with the line

**Comment by FriedrichStein** [comment]
Thanks a lot for the quick reply and fix!
Unfortunately the pictures will still show up, after collapsing the headers/lines:
![Jun-05-2021 17-43-29](https://user-images.githubusercontent.com/53973194/120897398-3a0e3a80-c626-11eb-8769-d046fc970f20.gif)
I tried the default theme and disabling all plug-ins, but it didn't had an impact.

**Comment by ozntel** [comment]
Which version of the plugin are you using?

**Comment by FriedrichStein** [comment]
It its 1.1.8

**Comment by ozntel** [comment]
After I changed within the new version, it works actually for me as you can see in the video:

https://user-images.githubusercontent.com/55187568/120904736-ffb89380-c64d-11eb-9684-8d18c55df442.mov

Can you restart your Obsidian and unload-load the plugin?

**Comment by FriedrichStein** [comment]
I did it, but nothing changes. 

But I did some experimenting and figured out, when it is happening to me: 
It only occurs, when the picture is on the last line under the heading/indention and there is no line afterwards.
When I create a line, even empty, after the image, it gets hidden properly, when collapsing the section.
