### ISSUE TITLE
[FEAT] Mobile support?

### ISSUE THREAD

**Issue by Quorafind** [ozntel/oz-image-in-editor-obsidian#3]
Cannot load on mobile for nodejs API, maybe you could use Obsidian's path api instead?

**Comment by ozntel** [comment]
Hi @Quorafind, unfortunately, I don't have an access to the mobile version, hence, it would be hard for me to implement something. If you have any suggestions, I am definitely open to include into the plugin.

**Comment by ozntel** [comment]
I am working on using Obsidian path API so that it can work also in the mobile version. Should be ready soon.
