### ISSUE TITLE
Suggestion: transclusions

### ISSUE THREAD

**Issue by DutchPete** [ozntel/oz-image-in-editor-obsidian#31]
I use transclusions/embeds a lot and was wondering if it is possible to have the plug-in render those too.

**Comment by ozntel** [comment]
Thank you for your suggestion. Since Obsidian already works on the WYSIWYG feature and this plugin will be redundant once the feature is implemented, I don't have a plan right now to implement embed rendering.

**Comment by DutchPete** [comment]
I understand your position, and I hope I did not upset you by asking this question in several places. It is just that I really like your plug-in.

Yes, the devs are working on WYSIWYG, or so it says on their roadmap, where it is even on the short term schedule. Nevertheless, following their placing it on the short term horizon, they decided to tackle Obsidian mobile first. Obs mobile seems to be making good progress, but in and of itself it is quite a big job, and I am not at all convinced that it will even be completed this year.

Towards the end of last year Licat indicated that WYSIWYG would probably be available in Q1/2021. We are now about to enter Q3 and we are nowhere near getting WYSIWYG.

All this to say that I would like to ask you to reconsider your decision to not proceed. If you remain on your position I will understand, I will be just as appreciative of what you have provided so far. I certainly hope I have not upset you with my insistence on this.

**Comment by DutchPete** [comment]
I am a bit confused. You refused to make transclusions visible in Edit mode because, as you said, "this plugin will be redundant once the feature is implemented", yet you added Excalidraw in the latests version 1.2.0.

I don't understand the logic.

**Comment by ozntel** [comment]
> I am a bit confused. You refused to make transclusions visible in Edit mode because, as you said, "this plugin will be > redundant once the feature is implemented", yet you added Excalidraw in the latests version 1.2.0.
>
> I don't understand the logic.

You should read the details more carefully:

- Version `1.2.0` was related to #34 
- `Excalidraw` support came with 1.1.0 in May: https://github.com/ozntel/oz-image-in-editor-obsidian/releases/tag/1.1.0
- Recently version `1.1.9` solved a bug for drawings: https://github.com/ozntel/oz-image-in-editor-obsidian/releases/tag/1.1.9

By the way, I am only an individual, who is programming during my free time. I have a full-time job (not related to programming), which I need to concentrate on. If I have any time left from family etc, I try to contribute to some projects like `Obsidian` without any financial expectation. I have already 4 plugins, which are listed in `Community Plugins` and I try to keep up-to-date and add some additional features if I have available time. I am happy that you have suggestion, however,  In my opinion, your approach is wrong with the insistence.

**Comment by DutchPete** [comment]
I apologize for the aggravation my insensitivity has caused you. It won't happen again.
