### ISSUE TITLE
PDF not rendering when page number added

### ISSUE THREAD

**Issue by M3NIX** [ozntel/oz-image-in-editor-obsidian#33]
right now rendering this in editor mode is working
```
![[file.pdf]]
```
but this not
```
![[file.pdf#page=8]]
```
Would be a nice feature since the obsidian preview can handle page numbers

**Comment by ozntel** [comment]
Kindly update your plugin from Community Plugins. PDF-s with page numbers should be rendered now.

**Comment by M3NIX** [comment]
Works perfectly. Thank you!
