### ISSUE TITLE
More hotkey to toggle features

### ISSUE THREAD

**Issue by b1uegh0st** [ozntel/oz-image-in-editor-obsidian#34]
Hi, 
 
 Firstly, thanks for the great recent releases (render choices, wysiwyg).

 This is a request that seems to be in-line with the directions other plug-ins in obsidian is going to: Give hotkey/command access to plug-in settings.

 **Use case:** I want to turn off/on the wysiwyg on the fly as I am editing (similar to the current "Toggle Render...").

 Thanks,
 NA

**Comment by ozntel** [comment]
I just released a version, which includes commands for settings so that you can assign `hotkey` for them. Please update the plugin from community plugins.

**Comment by b1uegh0st** [comment]
Great, thank you!!
