### ISSUE TITLE
Editor mode: invert and resise image does not work together

### ISSUE THREAD

**Issue by trungng2006** [ozntel/oz-image-in-editor-obsidian#37]
The invert mode work well for preview mode.

For editor mode, when only #invert was used, then it work.
![[Pasted image 20210706170912.png|#invert]]
However, when i add size adjustment, the image revert back to normal color (no invert)
![[Pasted image 20210706170912.png|#invert|800]

**Comment by trungng2006** [comment]
If i change the #invert and resize position, then invert work, but the image will not resize in both editor and preview mode.
![[Pasted image 20210706170912.png|800|#invert]

**Comment by ozntel** [comment]
![image](https://user-images.githubusercontent.com/55187568/124809770-cb900580-df60-11eb-8552-9bb27b28f497.png)

It works in Editor. Related to the Preview mode, you need to reach out to Obsidian developers since I am not handling the render process of the Preview mode.
