### ISSUE TITLE
Context Menu: Zoom image like Typora

### ISSUE THREAD

**Issue by CodingHuang** [ozntel/oz-image-in-editor-obsidian#39]
![image](https://user-images.githubusercontent.com/13886216/124741265-16ece880-df4e-11eb-8768-faec8973cb40.png)

**Comment by CodingHuang** [comment]
Additional features: when pasting images, the plugin can automatically zoom to a certain percentage

![image](https://user-images.githubusercontent.com/13886216/124743939-d0e55400-df50-11eb-85c6-1c01ff81721a.png)

**Comment by ozntel** [comment]
Kindly refer to the corresponding part of README:

https://github.com/ozntel/oz-image-in-editor-obsidian#image-view-size
