### ISSUE TITLE
links in WYSIWYG

### ISSUE THREAD

**Issue by oldjove** [ozntel/oz-image-in-editor-obsidian#40]
I'm really enjoying the plugin and the new (?) WYSIWYG-like experience. I've noticed though that MD links are not rendering quite right. E.g.

`[dispensation](https://www.lexico.com/definition/dispensation)`

appears as

dispensation<underline>https://www.lexico.com/definition/dispensation</underline>

**Comment by ozntel** [comment]
Yeah, I didn't like this, either.
I changed the styling a little bit so that it appears in a normal way even though you turn on `WYSIWYG-like experience`. It is in the new release.
I will implement if I find something better

**Comment by oldjove** [comment]
Ok, thanks for the explanation.
