### ISSUE TITLE
[FEAT] display images linked by external link from the folders outside of Obsidian vault

### ISSUE THREAD

**Issue by yo-goto** [ozntel/oz-image-in-editor-obsidian#41]
Hi, thank you for developing such a nice plugin!

I have a question and, if possible, want you to implement this feature.
Obsidian's preview mode can display images from almost everywhere in desktop folders with this format `![link name](file://path)`, for example `![my png image](file://Users/usrName/Desktop/my-png-image.png)`

At the moment, oz-image-in-editor can't display those images. Is this possible to display them in editor mode?

In my use case, it's convenient to dispatch images and put together them into a sub-folder under the project folder with many files out of Obsidian's vault. So, notes related to my projects have this kind of image link.

If possible, please consider adding the feature to enable showing images in preview mode.

Thanks.

**Comment by pjeby** [comment]
As a workaround, you can use URLs of the form `app://local/Users/username/desktop...`; that is, replace `file:///` with `app://local/`.

**Comment by yo-goto** [comment]
Thanks @pjeby.
This workaround works well. But to drag & drop images from Finder on macOS makes a link as `![link name](file://path)`, so this way needs me to replace the format every time.

@ozntel, can you support the format `![link name](file://path)` ?

**Comment by ozntel** [comment]
It should work now

**Comment by NomarCub** [comment]
It doesn't on Windows. I have an image in the root of my D drive called image.png.
When I drag it into Obsidian, it's URL gets decoded as `file:///D:%5Cimage.png`. I also tried `file:///D:/image.png` and finally `file://D:/image.png`. All work in preview, but only the third in editor.
Here's the console log:
![image](https://user-images.githubusercontent.com/5298006/126877535-a5ad3acb-e53a-4c68-b51f-501b0f9a710e.png)

**Comment by ozntel** [comment]
Can you try to replace your current `main.js` with the one I uploaded to Google Drive: [LINK](https://drive.google.com/file/d/1gOldxdNwHl49AMPiOOH8IAfidtDU3QMT/view?usp=sharing)
I don't have an access to a Windows PC at the moment.

**Comment by pjeby** [comment]
@ozntel You need to replace `file:///` with `app://local/` -- you aren't stripping the *third* slash.  A proper `file:` URL **always** has three slashes at the beginning.  (Technically, there can be a host name between the `//` and `/` but in practice nobody ever puts one there.)

**Comment by pjeby** [comment]
That is to say:

```js
if (filename.startsWith('file:///')) filename = filename.replace('file:///', 'app://local/');
```

If the URL has something after the first two slashes that isn't a slash, you *must not* replace it -- by the URL spec, text after the first two slashes is a hostname, which technically means you have to check if that's the machine's hostname before interpreting the URL.  It also means it's far more likely to be an incorrect URL, so making the user fix it manually is appropriate.

**Comment by yo-goto** [comment]
Sorry, I mistakenly wrote `file://`. The right format is `file:///` as @pjeby said.
But I've tested, and the feature works well on macOS.

**Comment by NomarCub** [comment]
The version from you Drive works @ozntel.
