### ISSUE TITLE
Iframe refreshes on edit

### ISSUE THREAD

**Issue by jacrify** [ozntel/oz-image-in-editor-obsidian#43]
Hi. I love this plugin. However I have a small issue.

I'm trying to embed YouTube iframes, and take notes in obsidian while watching the video. However when I hit enter, the iframe refreshes and loads back to the beginning. I've tried playing with various settings in the plugin but no luck.

Is there any way to make it so that the video does not refresh but I can still take notes?

For reference here's my note text:

`<iframe width="100%" height="500" src="https://www.youtube.com/embed/gYK3VDQsZJo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

**Comment by ozntel** [comment]
Hi, I am glad the plugin is useful. Unfortunately, there is something I don't have a control over with the `youtube` videos. They just refresh themselves. For the moment, I couldn't find a solution but I will see if there is anything can be done in the future.
