### ISSUE TITLE
Allow preview non-iframes videos 

### ISSUE THREAD

**Issue by Connor-yang96** [ozntel/oz-image-in-editor-obsidian#44]
Allow preview this video url , a non-iframes format. 

`![](https://www.youtube.com/watch?v=B-p03mokE8Q&pp=sAQA}`

for using Media Edxtended, timestamp plugin. 

Thanks.

**Comment by ozntel** [comment]
For the moment, I don't have in my plans to implement video rendering. I will see in the future if there is any place for this to add as enhancement.

**Comment by Connor-yang96** [comment]
I‘m confuse that why closed this issue and you said you will see in the future, for add as enhacement. 

Afraid you will forget this issue. 

How about add “enhancement ” tag for this issue ?
