### ISSUE TITLE
Feature Request - Render Fenced code blocks

### ISSUE THREAD

**Issue by timothyjlaurent** [ozntel/oz-image-in-editor-obsidian#47]
I really love the plugin!

It would be great if we had some way to indicate certain types of code-fences we would like to see rendered inline.

For example, you could say, render all `mermaid` and then you could see the effects of the diagram as it is edited.

**Comment by ozntel** [comment]
I'm glad the plugin is helpful. Since the main purpose of the plugin is to render `images` as a widget in the editor, I don't have a plan to implement rendering `mermaid` within the plugin. Thanks for the suggestion!

**Comment by timothyjlaurent** [comment]
So means is charts will only render as transclusions?

**Comment by ozntel** [comment]
Yes, you can render only using transclusions
