### ISSUE TITLE
Tasks in edit mode

### ISSUE THREAD

**Issue by jimclay75051** [ozntel/oz-image-in-editor-obsidian#49]
Hello, the WYSIWYG Like Experience is very nice. 

Just to let you know, in edit mode the tasks check boxes are not showing up. They show up in view mode but not the task mode.

Unless, in edit mode, your curser is on a task. Then the check box for that one task will show itself.

Thank you for the addon.

**Comment by DryIce1** [comment]
yes, this is the reason that I am not using the WYSIWYG function of this plugin.

- preview mode - checkboxes rendered as expected. e.g:
![image](https://user-images.githubusercontent.com/59501376/130007155-d84f27c9-9930-4a0f-b08d-1bbfba1aad62.png)
- edit mode - checkboxes disappear whether complete or incomplete. Completed tasks have strikethrough. If cursor in the active line then `[ ]` or `[x]` is displayed. e.g:
![image](https://user-images.githubusercontent.com/59501376/130007101-70698e4f-bda6-4839-bb08-6aa78ae3ddfa.png)

**expected outcome using WYSIWYG in edit mode**
1. complete and incomplete checkboxes should be displayed on inactive lines
2. checkboxes should be clickable

**Comment by jimclay75051** [comment]
I do disagree with not using the WYSIWYG Like Experience because of this bug. It otherwise works pretty well.

**Comment by ozntel** [comment]
I think it is not relevant anymore since I removed the support for CM5 and WYSIWYG mode went away. Thanks!
