### ISSUE TITLE
Page shifts down when typing

### ISSUE THREAD

**Issue by MichaelJBerk** [ozntel/oz-image-in-editor-obsidian#5]
As I type below an image, the page shifts down. When the image is offscreen, this does not occur

https://user-images.githubusercontent.com/49624366/116491166-40f79f80-a867-11eb-971a-068a3d4bc9e4.mp4

**Comment by ozntel** [comment]
Hi @MichaelJBerk can you download it again and try? There is one method that causes delay and I reverted back to the original version so that it doesn't cause such an issue.

**Comment by MichaelJBerk** [comment]
Thank you! This seems to have solved the problem
