### ISSUE TITLE
Render obsidian-admonition blocks

### ISSUE THREAD

**Issue by dariuszkowalski-com** [ozntel/oz-image-in-editor-obsidian#50]
There is a useful plugin:
https://github.com/valentine195/obsidian-admonition

which adds various block with particular styles.

I would like to see then in edit mode.

**Comment by ozntel** [comment]
Same as I mentioned for your request of `query` blocks, there is an additional plugin, which handles admonitions in the preview mode. It is not the core plugin of Obsidian. Therefore, I don't have a plan to implement it in `Image in Editor` plugin.
