### ISSUE TITLE
[Suggestion] Add table Preview

### ISSUE THREAD

**Issue by Mara-Li** [ozntel/oz-image-in-editor-obsidian#51]
I always struggle with table. It will be cool to have a preview of table after each edit.

**Comment by ozntel** [comment]
I wouldn't be able to support table preview separately but you can now preview the table with `block id` reference and render with the new `transclusion` feature in Editor. Just as a note, the changes in your table won't be visible in the preview unless you refresh the `transclusion` by, for instance, clicking space on the same line.
