### ISSUE TITLE
[BUG] Size of excalidraw in % doesn't work

### ISSUE THREAD

**Issue by dariuszkowalski-com** [ozntel/oz-image-in-editor-obsidian#52]
Now, when I add to md file:

![[Drawing .excalidraw.md|100%]]

I got a small preview -> % is omitted and interpreted as pixes.

![image](https://user-images.githubusercontent.com/37656900/130869642-781dcad5-9534-49da-8cc6-252dc48a736c.png)

In Preview Mode I got a normal 100% size an image

**Comment by ozntel** [comment]
Kindly check the `Image View Size` section of README. Percentage is not supported. You can use `#small`, `#x-small` for implementing percentages or write your own CSS:
https://github.com/ozntel/oz-image-in-editor-obsidian#image-view-size
