### ISSUE TITLE
![[Filename#Head123]] The link in double brackets cannot be displayed with the preview switch on, and the image cannot be displayed.

### ISSUE THREAD

**Issue by MILKMILKKING** [ozntel/oz-image-in-editor-obsidian#57]
As shown in the figure, the preview switch is turned on on the left side, and the preview mode is on the right side. The link in double brackets cannot be displayed with the preview switch on, and the image cannot be displayed.
Also, can you set ! [[Filename#Head123]]  the size of the preview box, for example in my image, I set the size of the preview box in the preview mode.

![image](https://user-images.githubusercontent.com/69726213/131302473-02d10c3d-efae-4ddb-bfd4-963f2f2aa318.png)

**Comment by ozntel** [comment]
`Wikilinks` are not common format in Markdown world. That's why they were not rendered in `Transclusions`. I included a manual clear function to detect them and convert to Markdown links manually. They should be rendered now.
