### ISSUE TITLE
Transclusions Rendering -> queries

### ISSUE THREAD

**Issue by dariuszkowalski-com** [ozntel/oz-image-in-editor-obsidian#58]
Transclusions Rendering seems to be a solution for my work. 
Now I see that it does not render ```query``` blocks?

It's a feature or a bug?

**Comment by ozntel** [comment]
It is not possible to pack all plugins that are created for preview and use within the Editor. They all have their own functions, event handlers etc. If the original plugin owner is in favor of supporting the Editor, there should be additional event handlers created by him/her. 

Transclusions in my plugin will only be rendered as pure "Markdown" blocks as they are rendered in different programs outside of Obsidian.
