### ISSUE TITLE
Inline image embedding doesn't work right

### ISSUE THREAD

**Issue by NomarCub** [ozntel/oz-image-in-editor-obsidian#59]
Images embedded in a line, not constituting a separate paragraph are still displayed as if they were in their own paragraph, and after their actual place of origin, not in it.
A simple example is Slack messages with emotes copied as images.

Markdown:

```md
some text with emojis ![:hushed:](https://a.slack-edge.com/production-standard-emoji-assets/13.0/google-medium/1f62f.png) in it
```

Preview:

![image](https://user-images.githubusercontent.com/5298006/131379937-94a53108-a635-4dd6-b537-0494e07dd450.png)

Editor:

![image](https://user-images.githubusercontent.com/5298006/131379899-19903efe-0c68-4688-aa89-10f4e3ab0faf.png)

**Comment by ozntel** [comment]
It is a normal behaviour. Line widgets in CM are located under the line, not within the line. Even though you have additional text, it will render the image after the line ends.
