### ISSUE TITLE
New block ref transclusion for multi line references joins each line together on a single line of text

### ISSUE THREAD

**Issue by GitMurf** [ozntel/oz-image-in-editor-obsidian#60]
With the new block ref transclusion feature, when I have a multi line block, the reference joins each line together on a single line of text. Looks like maybe it isn't respecting the `\n` line breaks or something?

![image](https://user-images.githubusercontent.com/64155612/131403282-eed4a9e5-99ac-4a69-b886-218fa8a2ffb5.png)

For code block references it works as expected:

![image](https://user-images.githubusercontent.com/64155612/131403448-2c952c8e-7c90-4e3b-adfb-68ab6bc109fb.png)

**Comment by ozntel** [comment]
The new release should solve this issue. I simply added custom options for `showdown` markdown converter to respect line breaks.

**Comment by GitMurf** [comment]
Thanks! I can confirm it is solved :)
