### ISSUE TITLE
Header Reference Embed transclusion dev console errors for Untitled XX pages

### ISSUE THREAD

**Issue by GitMurf** [ozntel/oz-image-in-editor-obsidian#62]
This is super weird but for whatever reasons Untitled pages are having issues with Header !embeds. I have recorded a video showing the couple issues.

Issue 1: On an untitled xx page, simply try to link to a header on that same page with ![[#]] and as soon as you type the hashtag you will see an error like this:

![image](https://user-images.githubusercontent.com/64155612/131751882-f5e700bd-9c7d-4600-bf99-8534a846a787.png)

Issue 2: When trying to link to a Header on an Untitled XX page:

![image](https://user-images.githubusercontent.com/64155612/131751963-b60a7463-5565-4ffe-b11c-11b725f1e4c7.png)

Here is a video showing both issues:

https://user-images.githubusercontent.com/64155612/131751779-40f6b795-ff46-4bf4-b2f9-d45618ee5c7b.mp4

**Comment by ozntel** [comment]
Issue should be resolved in the new release
