### ISSUE TITLE
[BUG] Dimensions 'alt' doesn't affect non-local images in preview mode

### ISSUE THREAD

**Issue by omerdn1** [ozntel/oz-image-in-editor-obsidian#63]
Hello,

Images in preview mode don't show up with custom dimensions.
`![100x100](some image)` - will show up with proper dimensions in edit mode but wouldn't take effect in preview mode.

Edit:
<img width="692" alt="Screen Shot 2021-09-02 at 17 16 43" src="https://user-images.githubusercontent.com/10265367/131860182-50383fa4-503d-49f3-86f9-3ce00da0d8fc.png">

Preview:
<img width="358" alt="Screen Shot 2021-09-02 at 17 17 06" src="https://user-images.githubusercontent.com/10265367/131860198-d3498e71-95f4-447b-bdbe-142ab7344daa.png">

I don't know if this is an intended behavior but I assumed it isn't since it kind of breaks consistency between views.

Love your plugin!

**Comment by omerdn1** [comment]
UPDATE: I just checked this feature with a local image and the resizing works on preview mode. So it seems like the bug only happens for non-local (URL) images.

**Comment by ozntel** [comment]
It is not scope of this plugin since it only manipulates the editor view. You need to report it to Obsidian, specifically to Licat.

**Comment by omerdn1** [comment]
@ozntel What's odd then is that local images do get affected. Is this done by Obsidian or your plugin?
If it's your plugin, shouldn't it be easy to implement the same mechanism for URL images?

**Comment by ozntel** [comment]
I don't handle anything in the preview mode. Obviously I included additional function to resize the images from internet and Obsidian didn't. I don't have a control over preview. The event handlers are totally different for preview and editor.
