### ISSUE TITLE
Transcluded Admonitions

### ISSUE THREAD

**Issue by DutchPete** [ozntel/oz-image-in-editor-obsidian#64]
![image](https://user-images.githubusercontent.com/10794265/132089293-fb10fbc3-669d-42bf-81b7-f6d6e08a9bf2.png)

Not quite right.

**Comment by ozntel** [comment]
It is not supposed to be. Plugin renders everything as pure `markdown`. Any kind of additional `view` options need to be written manually. There is a separate plugin for `Admonitions`. It is not possible for me to pack all `preview` plugins into single editor plugin and render as they are rendered in preview.

**Comment by DutchPete** [comment]
OK, I understand. I was just confused by the fact that with your plug-in enabled transcluded Admonitions are rendered as per the screenshot. My apologies for having bothered you.

**Comment by ozntel** [comment]
FYI - I released a new version, which partly renders the admonitions. It won't look exactly the same since I created all elements from scratch. But at least it won't be a Code Block. You need to enable this function from the settings.

**Comment by DutchPete** [comment]
Many thanks for this 👍 😀
I sent you a message via your website.
