### ISSUE TITLE
[Bug] Block ref render format tag as header

### ISSUE THREAD

**Issue by b1uegh0st** [ozntel/oz-image-in-editor-obsidian#65]
Hi,

Thanks for the great functionality. I've been searching around for a CSS way to do it but I guess it is more complex than that (not a pro but I inspected your implementation and see that it is code-mirror complex) .

Here is the problem after I tried it out a bit:
- If a tag is alone in a line in the referenced block.
- It will be rendered as H1

Not a huge problem once I figured it out (quick fix: just add some text before the tag). But I think there are people who likes to do tags on a separate line. And hope that the feedback 1. Encourage you to develop this functionality deeper. 2. May relate to other parts of how this implementation works.

Again, thanks for the great plugin and for implementing this. Look forward for it to move past "Experimental", get a shortcut and get a way to refresh faster.
NA
---

**Details**
Here's the original block
![image](https://user-images.githubusercontent.com/6695697/132108064-d44db5f1-498d-4187-b7ba-ffc532a96a0b.png)

Here's the rendered:
![image](https://user-images.githubusercontent.com/6695697/132108075-31509b96-fabd-4b16-94de-c0f396b4073d.png)

Inspection:
![image](https://user-images.githubusercontent.com/6695697/132108125-8a534f44-6c35-49d2-974f-cca6d35ded76.png)

**Comment by ozntel** [comment]
This is actually a bug that `showdown` markdown converter has. It doesn't differentiate the tag and h1 (with space)
I just released a version, which should solve the issue. Let me know if issue persists

**Comment by b1uegh0st** [comment]
Just checked. Works great now. Thanks!!
