### ISSUE TITLE
Block Ref / Header render with page ref inside it

### ISSUE THREAD

**Issue by b1uegh0st** [ozntel/oz-image-in-editor-obsidian#66]
This is a request for another of complex implementation. It is a nice-to-have I think.

 Hope for a cleaner implementation of this special case if possible. Meanwhile I will just try to reduce embedding the header which contain page reference.

 Thanks for a great plugin.
 NA
   
 --- 
 **Details**
   - Trying to embed this header 
![image](https://user-images.githubusercontent.com/6695697/132108625-78d1f9c6-e1fe-41e2-92de-1c6a5cefcb05.png)
 - The syntax that Obsidian understand: 
![image](https://user-images.githubusercontent.com/6695697/132108655-0d6b634e-752b-47c8-9df2-1bda7107a598.png)
 - Which rendered in preview as this: 
![image](https://user-images.githubusercontent.com/6695697/132108666-340bf15a-d69e-4770-9ff0-60ebe73b4449.png)

 - The syntax that the plugin understand (but render in double) 
![image](https://user-images.githubusercontent.com/6695697/132108690-f1608630-f4d3-4877-b4f3-f54f36d93a4d.png)

**Comment by b1uegh0st** [comment]
EDIT:
- Relaunch obsidian and the problem of double rendering went ago.
- Still cannot handle rendering the block ref without brackets `[[...]]`

**Comment by ozntel** [comment]
It should work now properly with the new release

**Comment by b1uegh0st** [comment]
Just updated and check. Works great now. 

Many thanks.
