### ISSUE TITLE
The latest update has changed the format

### ISSUE THREAD

**Issue by erdemalpkaya** [ozntel/oz-image-in-editor-obsidian#67]
Hi Ozan,

Thank you for the creating the plugin. 
I wanted to report that after the latest update of the plugin (1.5.0) I have lost one of the supported format from your plugin

I know this format actually does not appear in your introduction but it was working and it was pretty easy to use. 

So I was using ;

`![[example.png | width=700]]`

Did you stop as a purpose and how I can work with this format again?

**Comment by erdemalpkaya** [comment]
The issues has been closed. Please do not mind Ozan

**Comment by ozntel** [comment]
Hi Erdem, 

I actually made a change in version `1.4.7` to ensure that the sizing is compatible with Obsidian's preview mode.
It means only 2 formats should be assigned to image's width and height attributes:
 `![[example.png|700]]` or `![[example.png|700x400]]`
Any other format for `alt text` (including any string) is just rendered within the `alt` attribute.
If you remove any `width=` it should work fine in both editor and preview mode.

Let me know if you have any question.
