### ISSUE TITLE
Missing text in transclusion

### ISSUE THREAD

**Issue by quangnd159** [ozntel/oz-image-in-editor-obsidian#68]
Some text mysteriously goes missing in transclusion.

**Original block**:

> I think I'll adopt [[TfTHacker]]'s method–treating the vault's root folder as the workbench. This method is like [[Inbox Zero]] in the world of emails. So instead of falling into the trap of hoarding information, I'll treat input with care and serious thought. This will be my thinking space and I'll need to set aside at least an hour each day for it (best in the early morning–for I know I do not want to think much in the evening).

**Transcluded block**:

> I think I'll adopt TfTHacker in the world of emails. So instead of falling into the trap of hoarding information, I'll treat input with care and serious thought. This will be my thinking space and I'll need to set aside at least an hour each day for it (best in the early morning-for I know I do not want to think much in the evening).

Missing text right after "TfTHacker": 's method–treating the vault's root folder as the workbench. This method is like [[Inbox Zero]]

When I remove the brackets from TfTHacker, the block shows up properly.

**Comment by ozntel** [comment]
I just release a version, which solve the issue. Let me know if issue persists

**Comment by quangnd159** [comment]
Works great now. That was fast. Thanks!
