### ISSUE TITLE
size doesn't change

### ISSUE THREAD

**Issue by Mara-Li** [ozntel/oz-image-in-editor-obsidian#7]
![image](https://user-images.githubusercontent.com/30244939/116824629-854aae80-ab8b-11eb-9f47-55cb60fdb8be.png)
![image](https://user-images.githubusercontent.com/30244939/116824634-8c71bc80-ab8b-11eb-996a-15f1ba6b9bd3.png)
![image](https://user-images.githubusercontent.com/30244939/116824643-95fb2480-ab8b-11eb-9067-f8b3d1f9132b.png)

As you can see on the screen, the size doesn't change /:

I already try without css snippet and other plugin.

**Comment by ozntel** [comment]
Hi @Mara-Li, 
Could you please kindly go to community plugins and check for updates? 
I just released a version, which solves the CSS issue.

**Comment by Mara-Li** [comment]
Yup it's resolved ! Thanks :)

**Comment by ozntel** [comment]
I am glad it helped :)
