### ISSUE TITLE
[Transluction] Latex rendering

### ISSUE THREAD

**Issue by Mara-Li** [ozntel/oz-image-in-editor-obsidian#72]
As you do for Admonition, I would be cool to have also the latex rendering : 
![image](https://user-images.githubusercontent.com/30244939/132831719-cf46963f-de37-4b73-b850-41b1f52ffece.png)

In preview : 
![image](https://user-images.githubusercontent.com/30244939/132831765-129c4f1f-dcac-438a-988e-984dcf8d5926.png)

**Comment by ozntel** [comment]
It will be available after Obsidian's Public Release
