### ISSUE TITLE
Image visualization in FrontMatter

### ISSUE THREAD

**Issue by javiavid** [ozntel/oz-image-in-editor-obsidian#73]
This plugin is one of my favorites of obsidian, thank you very much!

I am began to use the Banners plugin (https://github.com/noatpad/obsidian-banners) and I would like to know if it is possible for your plugin to work with an image in the front patter in edit mode.

**Comment by ozntel** [comment]
Codemirror works with line widgets. Adding widget on the top of line or bottom of the line would maybe look a little bit similar but definitely far away from ideal. Unfortunately I don't have a plan for the moment to implement banner in the plugin.
