### ISSUE TITLE
Rendering link in WISIWIG mode

### ISSUE THREAD

**Issue by tonyxiao** [ozntel/oz-image-in-editor-obsidian#76]
Something like

```
[repo](https://github.com/ozntel/oz-image-in-editor-obsidian/issues/new)

```

Doesn't work in WISIWIG mode. It shows up as the full markdown text rather than only showing the image. 

The desired outcome is for it to only show the link label, not the url.

**Comment by ozntel** [comment]
Kindly refer to #40
