### ISSUE TITLE
Wanted: Tutorial how to fix WYSIWYG issues

### ISSUE THREAD

**Issue by davidszp** [ozntel/oz-image-in-editor-obsidian#78]
I found some unwanted WYSIWYG side effects with keywords generated by other plugins (e.g. advanced tables or annotations). I think it would be most efficient for us to fix these ourselves instead of asking Ozan to go through 300 plugins to ensure compatibility with all of them.

Say I want to fix the behavior of hiding `$` markdown code in case the character is part of a table formula in advanced tables. For example, when inside a table math formula such as `<!-- TBLFM: @8$2=(@4$2+@7$2);%.1f -->` WYSIWYG  should ignore the `$` instead of hiding it as it makes the formula unreadable. However, when found in regular text, it should hide it as it already does.

Where in the source do I find the WYSIWYG regex and replacement rules exactly?

**Comment by ozntel** [comment]
You can find the styles, which are turned on, when you select the WYSIWYG mode under the link:

https://github.com/ozntel/oz-image-in-editor-obsidian/blob/master/src/constants.ts

You can definitely overwrite any of them in your custom css if necessary.
