### ISSUE TITLE
Add Warning Message before converting whole vault

### ISSUE THREAD

**Issue by chrisgrieser** [ozntel/oz-image-in-editor-obsidian#83]
I accidentally selected to convert wikilinks from the whole vault, not only the active file. While it wasn't a big deal to convert everything back, it wouldn't hurt to add a warning modal before converting links in the entire vault to avoid accidents.

**Comment by ozntel** [comment]
I just released a version, which includes modals for vault scans

**Comment by chrisgrieser** [comment]
Thanks for the quick implementation!
