### ISSUE TITLE
[FEATURE REQUEST] render rich links

### ISSUE THREAD

**Issue by JJger148** [ozntel/oz-image-in-editor-obsidian#94]
There is an obsidian plugin "render rich links", which is very nice.
But it only renders in Preview Mode. 
It should be rendern in Edit mode like pictures.

**Comment by ozntel** [comment]
it won't be the same but now you can enable the feature to render External Markdown Links as rich link widget. Simply use `[Link](https://github.com)` syntax and the plugin should add a widget.

**Comment by JJger148** [comment]
Can you change it, so that it only shows the widget if a "!“ Is infant of the Link?

**Comment by ozntel** [comment]
> Can you change it, so that it only shows the widget if a "!“ Is infant of the Link?

It would be an image link, not external link
