### ISSUE TITLE
Embedded note (![[note]]) fails to render correctly if the note starts with a tag (#)

### ISSUE THREAD

**Issue by dummifiedme** [ozntel/oz-image-in-editor-obsidian#96]
Embedded note fails to render correctly if there is a note starting with a tag (#tag). Basically, the whole text of the note is converted to H1 or H2 sized (too big).

![image](https://user-images.githubusercontent.com/68785729/140784463-7c318d5f-4dd4-45e6-b4b5-6b3ceebf4064.png)

**Comment by ozntel** [comment]
It should be fixed in the new release
