### ISSUE TITLE
2 things: change color of admonition style sidebar in blockquote | Annotation Tags from Theme "Shimmering Focus"

### ISSUE THREAD

**Issue by ReaderGuy42** [ozntel/oz-image-in-editor-obsidian#97]
I just discovered the WYSIWYG mode of this plug-in (really cool) I was just wondering what part of the code was responsible for the color fo the side-bar that shows up in blockquotes?

And the other thing: Shimmering Focus has "Annotation Tags", which includes small unicode symbols next to a tag. Preview mode renders them as they are (https://github.com/chrisgrieser/shimmering-focus/#annotation-tags). 

WYSIWYG mode of your plugin gets rid of the symbol. Is there a way to include them?
Thanks :)

**Comment by ozntel** [comment]
Hi, you can find the WYSIWYG style under the link:

https://github.com/ozntel/oz-image-in-editor-obsidian/blob/master/src/cm5/constants.ts

You can definitely overwrite the parts, which are not appropriate for you, in your Custom CSS.

I'm focusing on more implementing the New Editor mode. Most probably Obsidian will also remove the support soon for the legacy editor :-)
