### ISSUE TITLE
How can I adjust the height of the preview box for quoting notes in the editing state?

### ISSUE THREAD

**Issue by MILKMILKKING** [ozntel/oz-image-in-editor-obsidian#98]
How can I adjust the height of the preview box for quoting notes in the editing state?
Sometimes when quoting another note, if that note has a lot of content, in the edit state, using the ! [[note]] will show all the contents of the note, which takes up a lot of editing space. How can I adjust the height of the preview box to be smaller? If I use CSS, what code should I write? I don't know anything about code.

**Comment by ozntel** [comment]
Within the new release the max height is fixed to 600px. You can change using `oz-transclusion-widget` class and overwrite `max-height` attribute
