### ISSUE TITLE
Render MathJax in Note Transclusion

### ISSUE THREAD

**Issue by joelmeyerhamme** [ozntel/oz-image-in-editor-obsidian#99]
Currently, LaTeX math in `$$` gets rendered as a code block.

```md
$\frac{1}{2}$ ^frac

![[#^frac]]
```

It would be preferable to show the rendered equation.

**Comment by ozntel** [comment]
Are you using the latest version of the plugin? It works properly:

![image](https://user-images.githubusercontent.com/55187568/143686241-5c67fc87-f409-40b3-900f-43a977c709f9.png)

**Comment by joelmeyerhamme** [comment]
Interesting, I'm on 1.7.1; Reinstalled and now it works fine. Sorry for the noise.
